spring.application.name=microservice-customer

spring.application.microservice.customer.url=http://localhost:8081/customer/api/v1/

devtools.restart=enabled


data.mongodb.uri=mongodb://localhost:27017


server.port=8081
server.servlet.context-path=/customer


